
'use client';

import React from 'react';
import { BedDouble } from 'lucide-react';
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from '@/components/ui/table';

export type StockItem = {
  name: string;
  category: string;
  current: number;
  min: number;
  max: number;
  unit: string;
  supplier: string;
  status: 'critical' | 'low' | 'normal';
};

type StockReportProps = {
  items: StockItem[];
};

export function StockReport({ items }: StockReportProps) {
  const statusColorMap: { [key: string]: string } = {
    critical: 'text-red-500',
    low: 'text-yellow-500',
    normal: 'text-green-500',
  };

  return (
    <div className="p-4">
      <header className="flex items-center justify-between mb-8 pb-4 border-b">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600 text-white">
            <BedDouble className="h-5 w-5" />
          </div>
          <span className="text-xl font-semibold">HotelVista - Stock Report</span>
        </div>
        <div className="text-right">
          <p className="font-medium">Date: {new Date().toLocaleDateString()}</p>
        </div>
      </header>

      <main>
        <h1 className="text-2xl font-bold mb-6">Inventory Status</h1>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="font-bold">Item Name</TableHead>
              <TableHead className="font-bold">Category</TableHead>
              <TableHead className="font-bold text-right">Current Stock</TableHead>
              <TableHead className="font-bold text-right">Min Stock</TableHead>
              <TableHead className="font-bold">Status</TableHead>
              <TableHead className="font-bold">Supplier</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {items.map((item) => (
              <TableRow key={item.name}>
                <TableCell className="font-medium">{item.name}</TableCell>
                <TableCell>{item.category}</TableCell>
                <TableCell className="text-right">{item.current} {item.unit}</TableCell>
                <TableCell className="text-right">{item.min} {item.unit}</TableCell>
                <TableCell>
                  <span className={`capitalize font-semibold ${statusColorMap[item.status]}`}>
                    {item.status}
                  </span>
                </TableCell>
                <TableCell>{item.supplier}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </main>

      <footer className="mt-12 pt-4 border-t text-center text-sm text-gray-500">
        <p>Generated by HotelVista Management System</p>
      </footer>
    </div>
  );
}
